### ISSUE TITLE
Better Stats

### ISSUE THREAD

**Issue by Eisfunke** [Eisfunke/Secret-Hitler-Telegram#4]
Cleaner stats using emojis.

**Comment by FRQDO** [comment]
No output is shown when invoking any of the commands `/deckstats`, `/boardstats`, `/anarchystats`.

Please provide server-side error stream logs to investigate.

**Comment by Eisfunke** [comment]
```
Nov 20 15:03:11 ruby python[2629]: 2018-11-20 15:03:11,692 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Nov 20 15:03:11 ruby python[2629]: Traceback (most recent call last):
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/venv/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
Nov 20 15:03:11 ruby python[2629]:     handler.handle_update(update, self)
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/venv/lib/python2.7/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
Nov 20 15:03:11 ruby python[2629]:     return self.callback(dispatcher.bot, update, **optional_args)
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/telegram_integration.py", line 149, in game_command_handler
Nov 20 15:03:11 ruby python[2629]:     reply = game.handle_message(player, command, args)
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 1022, in handle_message
Nov 20 15:03:11 ruby python[2629]:     if self.chancellor_legislate(policy):
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 520, in chancellor_legislate
Nov 20 15:03:11 ruby python[2629]:     self.pass_policy(enact)
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 589, in pass_policy
Nov 20 15:03:11 ruby python[2629]:     self.global_message(self.show(self))
Nov 20 15:03:11 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 157, in show
Nov 20 15:03:11 ruby python[2629]:     to_show, rest = things_to_show[0], things_to_show[1:]
Nov 20 15:03:11 ruby python[2629]: TypeError: 'Game' object does not support indexing
Nov 20 15:23:37 ruby python[2629]: 2018-11-20 15:23:37,184 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Nov 20 15:23:37 ruby python[2629]: Traceback (most recent call last):
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/venv/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
Nov 20 15:23:37 ruby python[2629]:     handler.handle_update(update, self)
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/venv/lib/python2.7/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
Nov 20 15:23:37 ruby python[2629]:     return self.callback(dispatcher.bot, update, **optional_args)
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/telegram_integration.py", line 149, in game_command_handler
Nov 20 15:23:37 ruby python[2629]:     reply = game.handle_message(player, command, args)
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 1022, in handle_message
Nov 20 15:23:37 ruby python[2629]:     if self.chancellor_legislate(policy):
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 520, in chancellor_legislate
Nov 20 15:23:37 ruby python[2629]:     self.pass_policy(enact)
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 589, in pass_policy
Nov 20 15:23:37 ruby python[2629]:     self.global_message(self.show(self))
Nov 20 15:23:37 ruby python[2629]:   File "/home/nicolas/secret-hitler/Secret_Hitler.py", line 157, in show
Nov 20 15:23:37 ruby python[2629]:     to_show, rest = things_to_show[0], things_to_show[1:]
Nov 20 15:23:37 ruby python[2629]: TypeError: 'Game' object does not support indexing
```
